In [1]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/interim/raw/elca_2010")
RGastos_2010 = pd.read_csv("RGastos-csv.tab", sep="\t")
RGastos_2010

,ola,consecutivo,cod_articulo,articulo,per_compra,compro,vr_compra,adq_sincompra,donde_obtuvo,vr_obtenido
0,1,121116,1,Pl???tano verde y maduro,No compra,NaN,NaN,No,NaN,NaN
1,1,121116,2,"Leche y derivados l???cteos (queso, cuajada, k...",Semanalmente,NaN,5500.0,No,NaN,NaN
2,1,121116,3,Huevos,Semanalmente,NaN,7300.0,No,NaN,NaN
3,1,121116,4,"Carne de res, cerdo o cordero, huevo y v???sceras",Semanalmente,NaN,20000.0,No,NaN,NaN
4,1,121116,5,Carne de gallina y pollo,No compra,NaN,NaN,No,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...
329611,1,226282,68,"Anillos, relojes y otros art???culos de joyer?...",NaN,No,NaN,No,NaN,NaN
329612,1,226282,69,Cuadros y obras originales de arte,NaN,No,NaN,No,NaN,NaN
329613,1,226282,70,Compra y sostenimiento de mascotas,NaN,No,NaN,No,NaN,NaN
329614,1,226282,71,Compra de computador personal,NaN,No,NaN,No,NaN,NaN
329615,1,226282,72,Primas o p???lizas de seguros,NaN,No,NaN,No,NaN,NaN

In [6]:
RGastos_2010["articulo"].dropna().unique()

array(['Pl???tano verde y maduro',
       'Leche y derivados l???cteos (queso, cuajada, kumis, yogur, crema de leche, mantequilla)',
       'Huevos', 'Carne de res, cerdo o cordero, huevo y v???sceras',
       'Carne de gallina y pollo',
       'Pescado de r???o o de mar u otros productos marinos frescos congelados',
       'Salchichas, jam???n, mortadela, salchich???n y otras carnes fr???as preparadas',
       'Papa com???n, papa criolla, yuca, arracacha, ???ame',
       'Arroz, pastas, avena, cuchuco, harinas, corn flakes y otros cereales',
       'Fr???jol seco, arveja seca, lentejas, garbanzos y otros granos',
       'Arveja verde, fr???jol verde, habichuela, zanahoria, tomate, lechuga, pepino, cebolla larga y cabezona y otras verduras',
       'Banano, guayaba, naranja, lim???n, mango, papaya, manzana, pi???a y otras frutas',
       'Aceite, manteca, margarina y otras grasas',
       'Az???car, sal, condimentos y salsas',
       'Panela, caf???, chocolate, t???',
       'Dulces, chitos, patacones, polvo para fresco y otros pasabocas',
       'Enlatados (arvejas, at???n, sardinas, salchichas)',
       'Galletas de sal y de dulce',
       'Gaseosas, maltas y jugos procesados',
       'Pago de agua diferente a acueducto (carro tanque, aguatero, agua embotellada)',
       'Comidas fuera del hogar y alimentos preparados fuera para consumo del hogar',
       'Cigarrillos y tabaco', 'F???sforos y encendedores',
       'Pasajes urbanos en bus, buseta, colectivo, ejecutivo, taxi, metro, transmilenio, pasajes intermunicipales',
       'Bebidas alcoh???licas (cerveza, aguardiente, ron, etc.)',
       'Combustible para veh???culo de uso del hogar',
       'Parqueo de veh???culo de uso del hogar', 'Lustradas de calzado',
       'Peri???dicos y revistas', 'Apuestas y loter???as',
       'Servicios p???blicos (acueducto, alcantarillado y aseo, energ???a el???ctrica, tel???fono, etc.)',
       'Servicio dom???stico de por d???as', 'Correo, fax, encomiendas',
       'Art???culos de aseo personal (crema dental, jab???n, champ???, papel higi???nico, desodorantes, toallas higi???nicas, pa???ales desechables, m???quinas y cuchillas de afeitar desechables)',
       'Art???culos para el aseo del hogar (detergentes, desinfectantes, escobas, ceras, servilletas, etc.)',
       'Algod???n, gasas desinfectantes, alcohol, curitas, anticonceptivos, aspirinas y otros elementos del botiqu???n',
       'Medias veladas para mujer',
       'Bombillos, pilas y otros art???culos el???ctricos, velas y velones',
       'Lavado y planchado de ropa fuera del hogar',
       'Corte de pelo y/o manicure',
       'Diversiones y entretenimiento (espect???culos, discotecas, cines, deportes, etc.)',
       'Empleados del servicio dom???stico internos',
       'Conexi???n o pago por uso de internet',
       'Pago del servicio de celular',
       'Gastos en salud (medicamentos, ex???menes, etc.)',
       'Gastos en educaci???n',
       'Ropa para hombre, mujer, ni???o y ni???a',
       'Calzado para hombres, mujer, ni???o y ni???a',
       'Reparaci???n de calzado y/o de vestuario',
       'Tela para vestuario u otros usos',
       'Reparaci???n, respuestos y mantenimiento de veh???culo de uso del hogar',
       'Libros, discos y CDs',
       'Muebles para el hogar (sala, comedor, camas.etc.)',
       'Reparaciones y mejoras de la vivienda (plomer???a, electricidad, pintura, resane, pa???etes)',
       'Colchones, cobijas, manteles y ropa de cama',
       'Ollas, vajillas, cubiertos y otros utensilios dom???sticos',
       'Nevera, estufa, TV, lavadora, brilladora, horno y otros aparatos electrodom???sticos y gasodom???sticos',
       'Pago de hoteles', 'Pasajes de avi???n',
       'Veh???culo, moto para uso del hogar',
       'Compra de bienes ra???ces diferentes a la vivienda que ocupa el hogar',
       'Cuotas extraordinarias de administracion o comunitarias',
       'Pago de impuestos de veh???culos de uso del hogar, seguro obligatorio, SOAT',
       'Impuesto a la renta y complementarios',
       'Seguro contra incendios o contra robo de la vivienda o veh???culos del hogar',
       'P???lizas o seguro de salud',
       'Anillos, relojes y otros art???culos de joyer???a, artesan???as, porcelanas, etc.',
       'Cuadros y obras originales de arte',
       'Compra y sostenimiento de mascotas',
       'Compra de computador personal', 'Primas o p???lizas de seguros'],
      dtype=object)

In [8]:
reemplazos = {
    "Pl???tano": "Plátano",
    "l???cteos": "lácteos",
    "v???sceras": "vísceras",
    "r???o": "río",
    "jam???n": "jamón",
    "salchich???n": "salchichón",
    "com???n": "común",
    "???ame": "ñame",
    "Fr???jol": "Fríjol",
    "fr???jol": "fríjol",
    "lim???n": "limón",
    "pi???a": "piña",
    "Az???car": "Azúcar",
    "caf???": "café",
    "t???": "té",
    "at???n": "atún",
    "F???sforos": "Fósforos",
    "alcoh???licas": "alcohólicas",
    "veh???culo": "vehículo",
    "veh???culos": "vehículos",
    "Peri???dicos": "Periódicos",
    "loter???as": "loterías",
    "p???blicos": "públicos",
    "energ???a": "energía",
    "el???ctrica": "eléctrica",
    "dom???stico": "doméstico",
    "d???as": "días",
    "Art???culos": "Artículos",
    "jab???n": "jabón",
    "champ???": "champú",
    "pa???ales": "pañales",
    "m???quinas": "máquinas",
    "Algod???n": "Algodón",
    "art???culos": "artículos",
    "el???ctricos": "eléctricos",
    "Peri???dicos": "Periódicos",
    "espect???culos": "espectáculos",
    "Conexi???n": "Conexión",
    "ex???menes": "exámenes",
    "educaci???n": "educación",
    "ni???o": "niño",
    "ni???a": "niña",
    "Reparaci???n": "Reparación",
    "respuestos": "repuestos",
    "plomer???a": "plomería",
    "pa???etes": "pañetes",
    "dom???sticos": "domésticos",
    "avi???n": "avión",
    "ra???ces": "raíces",
    "P???lizas": "Pólizas",
    "p???lizas": "pólizas",
    "joyer???a": "joyería",
    "artesan???as": "artesanías"
}

for viejo, nuevo in reemplazos.items():
    RGastos_2010["articulo"] = RGastos_2010["articulo"].str.replace(viejo, nuevo, regex=False)

RGastos_2010["articulo"].dropna().unique()

array(['Plátano verde y maduro',
       'Leche y derivados lácteos (queso, cuajada, kumis, yogur, crema de leche, mantequilla)',
       'Huevos', 'Carne de res, cerdo o cordero, huevo y vísceras',
       'Carne de gallina y pollo',
       'Pescado de río o de mar u otros productos marinos frescos congelados',
       'Salchichas, jamón, mortadela, salchichón y otras carnes fr???as preparadas',
       'Papa común, papa criolla, yuca, arracacha, ñame',
       'Arroz, pastas, avena, cuchuco, harinas, corn flakes y otros cereales',
       'Fríjol seco, arveja seca, lentejas, garbanzos y otros granos',
       'Arveja verde, fríjol verde, habichuela, zanahoria, tomate, lechuga, pepino, cebolla larga y cabezona y otras verduras',
       'Banano, guayaba, naranja, limón, mango, papaya, manzana, piña y otras frutas',
       'Aceite, manteca, margarina y otras grasas',
       'Azúcar, sal, condimentos y salsas', 'Panela, café, chocolate, té',
       'Dulces, chitos, patacones, polvo para fresco y otros pasabocas',
       'Enlatados (arvejas, atén, sardinas, salchichas)',
       'Galletas de sal y de dulce',
       'Gaseosas, maltas y jugos procesados',
       'Pago de agua diferente a acueducto (carro tanque, aguatero, agua embotellada)',
       'Comidas fuera del hogar y alimentos preparados fuera para consumo del hogar',
       'Cigarrillos y tabaco', 'Fósforos y encendedores',
       'Pasajes urbanos en bus, buseta, colectivo, ejecutivo, taxi, metro, transmilenio, pasajes intermunicipales',
       'Bebidas alcohólicas (cerveza, aguardiente, ron, etc.)',
       'Combustible para vehículo de uso del hogar',
       'Parqueo de vehículo de uso del hogar', 'Lustradas de calzado',
       'Periódicos y revistas', 'Apuestas y loterías',
       'Servicios públicos (acueducto, alcantarillado y aseo, energía eléctrica, tel???fono, etc.)',
       'Servicio doméstico de por días', 'Correo, fax, encomiendas',
       'Artéculos de aseo personal (crema dental, jabón, champú, papel higi???nico, desodorantes, toallas higi???nicas, pañales desechables, máquinas y cuchillas de afeitar desechables)',
       'Artéculos para el aseo del hogar (detergentes, desinfectantes, escobas, ceras, servilletas, etc.)',
       'Algodón, gasas desinfectantes, alcohol, curitas, anticonceptivos, aspirinas y otros elementos del botiqu???n',
       'Medias veladas para mujer',
       'Bombillos, pilas y otros artéculos eléctricos, velas y velones',
       'Lavado y planchado de ropa fuera del hogar',
       'Corte de pelo y/o manicure',
       'Diversiones y entretenimiento (espectéculos, discotecas, cines, deportes, etc.)',
       'Empleados del servicio doméstico internos',
       'Conexión o pago por uso de internet',
       'Pago del servicio de celular',
       'Gastos en salud (medicamentos, exámenes, etc.)',
       'Gastos en educación', 'Ropa para hombre, mujer, niño y niña',
       'Calzado para hombres, mujer, niño y niña',
       'Reparación de calzado y/o de vestuario',
       'Tela para vestuario u otros usos',
       'Reparación, repuestos y mantenimiento de vehículo de uso del hogar',
       'Libros, discos y CDs',
       'Muebles para el hogar (sala, comedor, camas.etc.)',
       'Reparaciones y mejoras de la vivienda (plomería, electricidad, pintura, resane, pañetes)',
       'Colchones, cobijas, manteles y ropa de cama',
       'Ollas, vajillas, cubiertos y otros utensilios domésticos',
       'Nevera, estufa, TV, lavadora, brilladora, horno y otros aparatos electrodomésticos y gasodomésticos',
       'Pago de hoteles', 'Pasajes de avión',
       'Veh???culo, moto para uso del hogar',
       'Compra de bienes raíces diferentes a la vivienda que ocupa el hogar',
       'Cuotas extraordinarias de administracion o comunitarias',
       'Pago de impuestos de vehículos de uso del hogar, seguro obligatorio, SOAT',
       'Impuesto a la renta y complementarios',
       'Seguro contra incendios o contra robo de la vivienda o vehículos del hogar',
       'Pólizas o seguro de salud',
       'Anillos, relojes y otros artéculos de joyería, artesanías, porcelanas, etc.',
       'Cuadros y obras originales de arte',
       'Compra y sostenimiento de mascotas',
       'Compra de computador personal', 'Primas o pólizas de seguros'],
      dtype=object)

In [8]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/interim/raw/elca_2013")
RActivos_hogar_2013 = pd.read_csv("RActivos_hogar-csv.tab", sep="\t")
RActivos_hogar_2013

,ola,zona,region,llave,consecutivo,hogar,tiro_animal,n_tiro_animal,tractor,n_tractor,...,n_avescorral,caballos,n_caballos,ovejas,n_ovejas,colmenas,n_colmenas,otros_anim,n_otros_anim,n_otro_cual
0,2,Rural,Atl???ntica,11141601,111416,1,Si,1.0,No,NaN,...,50.0,S???,2.0,S???,9.0,No,NaN,No,NaN,
1,2,Rural,Atl???ntica,11342405,113424,5,No,NaN,No,NaN,...,80.0,No,NaN,No,NaN,No,NaN,No,NaN,
2,2,Rural,Oriental,11565501,115655,1,Si,1.0,No,NaN,...,19.0,No,NaN,S???,3.0,No,NaN,No,NaN,
3,2,Rural,Atl???ntica,11641001,116410,1,No,NaN,No,NaN,...,30.0,S???,3.0,No,NaN,No,NaN,No,NaN,
4,2,Rural,Atl???ntica,11641101,116411,1,No,NaN,No,NaN,...,12.0,No,NaN,No,NaN,No,NaN,No,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4334,2,Rural,Eje Cafetero,22628601,226286,1,No,NaN,No,NaN,...,7.0,No,NaN,No,NaN,No,NaN,No,NaN,
4335,2,Rural,Eje Cafetero,22628701,226287,1,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
4336,2,Rural,Eje Cafetero,22628801,226288,1,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
4337,2,Rural,Eje Cafetero,22628901,226289,1,No,NaN,No,NaN,...,8.0,No,NaN,No,NaN,No,NaN,No,NaN,
4338,2,Rural,Oriental,22662601,226626,1,No,NaN,No,NaN,...,13.0,No,NaN,No,NaN,No,NaN,No,NaN,

In [9]:
set(RActivos_hogar_2010) - set(RActivos_hogar_2013)

{'abejas',
 'n_abejas',
 'n_oanim',
 'n_peces',
 'peces',
 'vr_alquiler_abrevad',
 'vr_alquiler_benef',
 'vr_alquiler_bodega',
 'vr_alquiler_bombagua',
 'vr_alquiler_camion',
 'vr_alquiler_corral',
 'vr_alquiler_cosechadora',
 'vr_alquiler_equiprie',
 'vr_alquiler_establo',
 'vr_alquiler_fespald',
 'vr_alquiler_fmotor',
 'vr_alquiler_guadanadora',
 'vr_alquiler_inverna',
 'vr_alquiler_marroz',
 'vr_alquiler_motosierra',
 'vr_alquiler_oactivo',
 'vr_alquiler_ordena',
 'vr_alquiler_otros_tractor',
 'vr_alquiler_plantelec',
 'vr_alquiler_plantgas',
 'vr_alquiler_sembradora',
 'vr_alquiler_silos',
 'vr_alquiler_tiro_animal',
 'vr_alquiler_tractor',
 'vr_alquiler_trapiche'}

In [10]:
set(RActivos_hogar_2013) - set(RActivos_hogar_2010)

{'colmenas',
 'estanque',
 'hogar',
 'llave',
 'n_colmenas',
 'n_estanque',
 'n_otro_cual',
 'n_otros_anim',
 'n_picapasto',
 'picapasto',
 'region',
 'zona'}

In [18]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/interim/raw/elca_2016")
RActivos_hogar_2016 = pd.read_csv("RActivos_hogar-csv.tab", sep="\t")
RActivos_hogar_2016

,ola,consecutivo,hogar,llave,hogar_n16,llave_n16,tiro_animal,n_tiro_animal,tractor,n_tractor,...,n_avescorral,caballos,n_caballos,ovejas,n_ovejas,colmenas,n_colmenas,otros_anim,n_otros_anim,n_otro_cual
0,3,111207,2.0,11120702.0,2,1112070202,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
1,3,111416,1.0,11141601.0,5,1114160105,No,NaN,Si,1.0,...,6.0,No,NaN,No,NaN,No,NaN,No,NaN,
2,3,114200,1.0,11420001.0,1,1142000101,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3,3,114220,NaN,NaN,7,1142200707,No,NaN,No,NaN,...,20.0,No,NaN,No,NaN,No,NaN,No,NaN,
4,3,115655,1.0,11565501.0,1,1156550101,No,NaN,No,NaN,...,4.0,No,NaN,No,NaN,No,NaN,No,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3888,3,226287,1.0,22628701.0,1,2262870101,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3889,3,226287,1.0,22628701.0,2,2262870102,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3890,3,226288,1.0,22628801.0,1,2262880101,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3891,3,226289,1.0,22628901.0,1,2262890101,No,NaN,No,NaN,...,15.0,No,NaN,No,NaN,No,NaN,No,NaN,
3892,3,226621,1.0,22662101.0,1,2266210101,No,NaN,No,NaN,...,11.0,No,NaN,No,NaN,No,NaN,No,NaN,

In [13]:
columnas = sorted(
    set(RActivos_hogar_2010.columns).union(RActivos_hogar_2013.columns)
)

df1 = RActivos_hogar_2010.reindex(columns=columnas)
df2 = RActivos_hogar_2013.reindex(columns=columnas)

RActivos_hogar_2010_2013 = pd.concat(
    [RActivos_hogar_2010, RActivos_hogar_2013],
    ignore_index=True
)
RActivos_hogar_2010_2013

,ola,consecutivo,tiro_animal,n_tiro_animal,vr_alquiler_tiro_animal,tractor,n_tractor,vr_alquiler_tractor,otros_tractor,n_otros_tractor,...,llave,hogar,estanque,n_estanque,picapasto,n_picapasto,colmenas,n_colmenas,n_otros_anim,n_otro_cual
0,1,121116,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,121117,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,121118,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,121119,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,121120,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8912,2,226286,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628601.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8913,2,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628701.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8914,2,226288,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628801.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8915,2,226289,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628901.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8916,2,226626,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22662601.0,1.0,No,NaN,No,NaN,No,NaN,NaN,

In [ ]:
print(RActivos_hogar_2010.shape)
print(RActivos_hogar_2013.shape)
print(RActivos_hogar_2010_2013.shape)
print(4578+4339)

(4578, 97)
(4339, 79)
(8917, 109)
8917

In [19]:
columnas = sorted(
    set(RActivos_hogar_2010_2013.columns).union(RActivos_hogar_2016.columns)
)

df1 = RActivos_hogar_2010_2013.reindex(columns=columnas)
df2 = RActivos_hogar_2016.reindex(columns=columnas)

RActivos_hogar_unido = pd.concat(
    [RActivos_hogar_2010_2013, RActivos_hogar_2016],
    ignore_index=True
)
RActivos_hogar_unido

,ola,consecutivo,tiro_animal,n_tiro_animal,vr_alquiler_tiro_animal,tractor,n_tractor,vr_alquiler_tractor,otros_tractor,n_otros_tractor,...,n_estanque,picapasto,n_picapasto,colmenas,n_colmenas,n_otros_anim,n_otro_cual,hogar_n16,llave_n16,n_invernadro
0,1,121116,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,121117,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,121118,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,121119,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,121120,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12805,3,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.262870e+09,NaN
12806,3,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,2.0,2.262870e+09,NaN
12807,3,226288,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.262880e+09,NaN
12808,3,226289,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,Si,3.0,No,NaN,NaN,,1.0,2.262890e+09,NaN
12809,3,226621,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.266210e+09,1.0

In [20]:
print(RActivos_hogar_2010_2013.shape)
print(RActivos_hogar_2016.shape)
print(RActivos_hogar_unido.shape)

(8917, 109)
(3893, 79)
(12810, 112)

In [22]:
ruta = "/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed/RActivos_hogar_unido.csv"

RActivos_hogar_unido.to_csv(
    ruta,
    index=False,
    encoding="utf-8-sig"
)

In [10]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed")
gastos_elca_longitudinal = pd.read_csv("gastos_elca_longitudinal.csv", sep=",")
gastos_elca_longitudinal

,llave_n16,llave,consecutivo,hogar_n16,hogar,ola,zona,total_items_comprados,total_gasto,gasto_aceite_manteca_margarina_y_otras_grasas,...,vr_ropa_para_hombre_mujer_nino_y_nina,vr_salchichas_jamon_mortadela_salchichon_y_otras_carnes_frias_preparadas,vr_salud_de_todos_los_miembros_del_hogar_incluya_medicina_prepagada,vr_salud_medicamentos_examenes_consultas_etc,vr_salud_terapias_hospitalizaciones_etc_diferentes_a_las_reportadas_en_403_l,vr_seguro_contra_incendios_o_contra_robo_de_la_vivienda_o_vehiculos_de_uso_del_hogar,vr_servicio_domestico_por_dias,vr_servicios_publicos_acueducto_alcantarillado_y_aseo_energia_electrica_telefono_fijo_gas_etc,vr_tela_para_vestuario_u_otros_usos,vr_vehiculo_moto_para_uso_del_hogar
0,NaN,NaN,111001,NaN,NaN,1,Urbano,11.0,495500.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,153000.0,NaN,NaN
1,NaN,NaN,111002,NaN,NaN,1,Urbano,13.0,527200.0,NaN,...,150000.0,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,NaN,NaN
2,NaN,NaN,111003,NaN,NaN,1,Urbano,17.0,3832500.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,90000.0,NaN,NaN
3,NaN,NaN,111004,NaN,NaN,1,Urbano,17.0,1873000.0,NaN,...,700000.0,NaN,NaN,NaN,NaN,NaN,NaN,60000.0,NaN,NaN
4,NaN,NaN,111006,NaN,NaN,1,Urbano,10.0,241500.0,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,2.262870e+09,22628701.0,226287,1.0,NaN,3,Rural,30.0,1643700.0,1.0,...,25000.0,5000.0,NaN,NaN,NaN,NaN,NaN,200000.0,NaN,NaN
27928,2.262870e+09,22628701.0,226287,2.0,NaN,3,Rural,19.0,626700.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27929,2.262880e+09,22628801.0,226288,1.0,NaN,3,Rural,27.0,865400.0,1.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,50000.0,NaN
27930,2.262890e+09,22628901.0,226289,1.0,NaN,3,Rural,31.0,1337550.0,1.0,...,78000.0,NaN,NaN,6700.0,NaN,NaN,NaN,47000.0,NaN,NaN
27931,2.266210e+09,22662101.0,226621,1.0,NaN,3,Rural,36.0,1884100.0,1.0,...,NaN,8000.0,NaN,9000.0,NaN,NaN,NaN,60000.0,NaN,NaN