In [4]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/interim/raw/elca_2010")
RActivos_hogar_2010 = pd.read_csv("RActivos_hogar-csv.tab", sep="\t")
RActivos_hogar_2010

,ola,consecutivo,tiro_animal,n_tiro_animal,vr_alquiler_tiro_animal,tractor,n_tractor,vr_alquiler_tractor,otros_tractor,n_otros_tractor,...,peces,n_peces,caballos,n_caballos,ovejas,n_ovejas,abejas,n_abejas,otros_anim,n_oanim
0,1,121116,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
1,1,121117,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
2,1,121118,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
3,1,121119,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
4,1,121120,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4573,1,226286,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
4574,1,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
4575,1,226288,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
4576,1,226289,Si,1.0,0,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN
4577,1,226290,No,NaN,NaN,No,NaN,NaN,No,NaN,...,No,NaN,No,NaN,No,NaN,No,NaN,No,NaN

In [6]:
RActivos_hogar_2010["consecutivo"].nunique()

4578

In [8]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/interim/raw/elca_2013")
RActivos_hogar_2013 = pd.read_csv("RActivos_hogar-csv.tab", sep="\t")
RActivos_hogar_2013

,ola,zona,region,llave,consecutivo,hogar,tiro_animal,n_tiro_animal,tractor,n_tractor,...,n_avescorral,caballos,n_caballos,ovejas,n_ovejas,colmenas,n_colmenas,otros_anim,n_otros_anim,n_otro_cual
0,2,Rural,Atl???ntica,11141601,111416,1,Si,1.0,No,NaN,...,50.0,S???,2.0,S???,9.0,No,NaN,No,NaN,
1,2,Rural,Atl???ntica,11342405,113424,5,No,NaN,No,NaN,...,80.0,No,NaN,No,NaN,No,NaN,No,NaN,
2,2,Rural,Oriental,11565501,115655,1,Si,1.0,No,NaN,...,19.0,No,NaN,S???,3.0,No,NaN,No,NaN,
3,2,Rural,Atl???ntica,11641001,116410,1,No,NaN,No,NaN,...,30.0,S???,3.0,No,NaN,No,NaN,No,NaN,
4,2,Rural,Atl???ntica,11641101,116411,1,No,NaN,No,NaN,...,12.0,No,NaN,No,NaN,No,NaN,No,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4334,2,Rural,Eje Cafetero,22628601,226286,1,No,NaN,No,NaN,...,7.0,No,NaN,No,NaN,No,NaN,No,NaN,
4335,2,Rural,Eje Cafetero,22628701,226287,1,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
4336,2,Rural,Eje Cafetero,22628801,226288,1,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
4337,2,Rural,Eje Cafetero,22628901,226289,1,No,NaN,No,NaN,...,8.0,No,NaN,No,NaN,No,NaN,No,NaN,
4338,2,Rural,Oriental,22662601,226626,1,No,NaN,No,NaN,...,13.0,No,NaN,No,NaN,No,NaN,No,NaN,

In [9]:
set(RActivos_hogar_2010) - set(RActivos_hogar_2013)

{'abejas',
 'n_abejas',
 'n_oanim',
 'n_peces',
 'peces',
 'vr_alquiler_abrevad',
 'vr_alquiler_benef',
 'vr_alquiler_bodega',
 'vr_alquiler_bombagua',
 'vr_alquiler_camion',
 'vr_alquiler_corral',
 'vr_alquiler_cosechadora',
 'vr_alquiler_equiprie',
 'vr_alquiler_establo',
 'vr_alquiler_fespald',
 'vr_alquiler_fmotor',
 'vr_alquiler_guadanadora',
 'vr_alquiler_inverna',
 'vr_alquiler_marroz',
 'vr_alquiler_motosierra',
 'vr_alquiler_oactivo',
 'vr_alquiler_ordena',
 'vr_alquiler_otros_tractor',
 'vr_alquiler_plantelec',
 'vr_alquiler_plantgas',
 'vr_alquiler_sembradora',
 'vr_alquiler_silos',
 'vr_alquiler_tiro_animal',
 'vr_alquiler_tractor',
 'vr_alquiler_trapiche'}

In [10]:
set(RActivos_hogar_2013) - set(RActivos_hogar_2010)

{'colmenas',
 'estanque',
 'hogar',
 'llave',
 'n_colmenas',
 'n_estanque',
 'n_otro_cual',
 'n_otros_anim',
 'n_picapasto',
 'picapasto',
 'region',
 'zona'}

In [18]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/interim/raw/elca_2016")
RActivos_hogar_2016 = pd.read_csv("RActivos_hogar-csv.tab", sep="\t")
RActivos_hogar_2016

,ola,consecutivo,hogar,llave,hogar_n16,llave_n16,tiro_animal,n_tiro_animal,tractor,n_tractor,...,n_avescorral,caballos,n_caballos,ovejas,n_ovejas,colmenas,n_colmenas,otros_anim,n_otros_anim,n_otro_cual
0,3,111207,2.0,11120702.0,2,1112070202,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
1,3,111416,1.0,11141601.0,5,1114160105,No,NaN,Si,1.0,...,6.0,No,NaN,No,NaN,No,NaN,No,NaN,
2,3,114200,1.0,11420001.0,1,1142000101,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3,3,114220,NaN,NaN,7,1142200707,No,NaN,No,NaN,...,20.0,No,NaN,No,NaN,No,NaN,No,NaN,
4,3,115655,1.0,11565501.0,1,1156550101,No,NaN,No,NaN,...,4.0,No,NaN,No,NaN,No,NaN,No,NaN,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3888,3,226287,1.0,22628701.0,1,2262870101,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3889,3,226287,1.0,22628701.0,2,2262870102,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3890,3,226288,1.0,22628801.0,1,2262880101,No,NaN,No,NaN,...,NaN,No,NaN,No,NaN,No,NaN,No,NaN,
3891,3,226289,1.0,22628901.0,1,2262890101,No,NaN,No,NaN,...,15.0,No,NaN,No,NaN,No,NaN,No,NaN,
3892,3,226621,1.0,22662101.0,1,2266210101,No,NaN,No,NaN,...,11.0,No,NaN,No,NaN,No,NaN,No,NaN,

In [13]:
columnas = sorted(
    set(RActivos_hogar_2010.columns).union(RActivos_hogar_2013.columns)
)

df1 = RActivos_hogar_2010.reindex(columns=columnas)
df2 = RActivos_hogar_2013.reindex(columns=columnas)

RActivos_hogar_2010_2013 = pd.concat(
    [RActivos_hogar_2010, RActivos_hogar_2013],
    ignore_index=True
)
RActivos_hogar_2010_2013

,ola,consecutivo,tiro_animal,n_tiro_animal,vr_alquiler_tiro_animal,tractor,n_tractor,vr_alquiler_tractor,otros_tractor,n_otros_tractor,...,llave,hogar,estanque,n_estanque,picapasto,n_picapasto,colmenas,n_colmenas,n_otros_anim,n_otro_cual
0,1,121116,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,121117,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,121118,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,121119,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,121120,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8912,2,226286,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628601.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8913,2,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628701.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8914,2,226288,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628801.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8915,2,226289,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22628901.0,1.0,No,NaN,No,NaN,No,NaN,NaN,
8916,2,226626,No,NaN,NaN,No,NaN,NaN,No,NaN,...,22662601.0,1.0,No,NaN,No,NaN,No,NaN,NaN,

In [ ]:
print(RActivos_hogar_2010.shape)
print(RActivos_hogar_2013.shape)
print(RActivos_hogar_2010_2013.shape)
print(4578+4339)

(4578, 97)
(4339, 79)
(8917, 109)
8917

In [19]:
columnas = sorted(
    set(RActivos_hogar_2010_2013.columns).union(RActivos_hogar_2016.columns)
)

df1 = RActivos_hogar_2010_2013.reindex(columns=columnas)
df2 = RActivos_hogar_2016.reindex(columns=columnas)

RActivos_hogar_unido = pd.concat(
    [RActivos_hogar_2010_2013, RActivos_hogar_2016],
    ignore_index=True
)
RActivos_hogar_unido

,ola,consecutivo,tiro_animal,n_tiro_animal,vr_alquiler_tiro_animal,tractor,n_tractor,vr_alquiler_tractor,otros_tractor,n_otros_tractor,...,n_estanque,picapasto,n_picapasto,colmenas,n_colmenas,n_otros_anim,n_otro_cual,hogar_n16,llave_n16,n_invernadro
0,1,121116,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,121117,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,121118,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,121119,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,121120,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12805,3,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.262870e+09,NaN
12806,3,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,2.0,2.262870e+09,NaN
12807,3,226288,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.262880e+09,NaN
12808,3,226289,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,Si,3.0,No,NaN,NaN,,1.0,2.262890e+09,NaN
12809,3,226621,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.266210e+09,1.0

In [20]:
print(RActivos_hogar_2010_2013.shape)
print(RActivos_hogar_2016.shape)
print(RActivos_hogar_unido.shape)

(8917, 109)
(3893, 79)
(12810, 112)

In [ ]:
ruta = "/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed/RActivos_hogar_unido.parquet"

RActivos_hogar_unido.to_parquet(
    ruta,
    index=False,
    engine="pyarrow",
)