In [2]:
import os 
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed/")
df = pd.read_parquet("choques_elca_longitudinal.parquet")
df.head(50)

,llave_n16,llave,consecutivo,hogar_n16,hogar,ola,zona,total_choques,choque_abandono_del_hogar_por_parte_de_un_menor_de_18_anos,choque_abandono_del_que_era_jefe_del_hogar_o_del_conyuge,...,resp_se_cambiaron_a_una_vivienda_mas_economica,resp_se_endeudaron_con_familiares_o_amigos,resp_se_endeudaron_con_un_banco_o_entidad_financiera,resp_se_reubicaron,resp_tomaron_un_seguro,resp_tuvieron_que_cambiar_de_municipio_o_departamento,resp_uno_o_mas_miembros_del_hogar_cambiaron_de_residencia,resp_uno_o_mas_miembros_del_hogar_salieron_del_pais,resp_usaron_algun_seguro,resp_vendieron_bienes_o_activos
0,NaN,NaN,111003,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
1,NaN,NaN,111006,NaN,NaN,1,Urbano,3.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
2,NaN,NaN,111007,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
3,NaN,NaN,111011,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
4,NaN,NaN,111012,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
5,NaN,NaN,111013,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
6,NaN,NaN,111015,NaN,NaN,1,Urbano,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,2.0,0.0,0.0,0.0
7,NaN,NaN,111016,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
8,NaN,NaN,111018,NaN,NaN,1,Urbano,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
9,NaN,NaN,111110,NaN,NaN,1,Urbano,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
10,NaN,NaN,111111,NaN,NaN,1,Urbano,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
11,NaN,NaN,111203,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
12,NaN,NaN,111206,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
13,NaN,NaN,111210,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
14,NaN,NaN,111219,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
15,NaN,NaN,111221,NaN,NaN,1,Urbano,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
16,NaN,NaN,111312,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
17,NaN,NaN,111403,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
18,NaN,NaN,111408,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
19,NaN,NaN,111416,NaN,NaN,1,Urbano,2.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,0.0
20,NaN,NaN,111500,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
21,NaN,NaN,111501,NaN,NaN,1,Urbano,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
22,NaN,NaN,111503,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
23,NaN,NaN,111512,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
24,NaN,NaN,111522,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
25,NaN,NaN,111536,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
26,NaN,NaN,111551,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
27,NaN,NaN,111562,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
28,NaN,NaN,111563,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
29,NaN,NaN,111565,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
30,NaN,NaN,111567,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
31,NaN,NaN,111653,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
32,NaN,NaN,111655,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
33,NaN,NaN,111659,NaN,NaN,1,Urbano,2.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
34,NaN,NaN,111660,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
35,NaN,NaN,112004,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
36,NaN,NaN,112007,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
37,NaN,NaN,112112,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
38,NaN,NaN,112123,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
39,NaN,NaN,112203,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,1.0,0.0,0.0,0.0
40,NaN,NaN,112224,NaN,NaN,1,Urbano,1.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
41,NaN,NaN,113002,NaN,NaN,1,Urbano,4.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
42,NaN,NaN,113007,NaN,NaN,1,Urbano,3.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
43,NaN,NaN,113010,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
44,NaN,NaN,113011,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
45,NaN,NaN,113012,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
46,NaN,NaN,113013,NaN,NaN,1,Urbano,3.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
47,NaN,NaN,113014,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
48,NaN,NaN,113016,NaN,NaN,1,Urbano,2.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
49,NaN,NaN,113018,NaN,NaN,1,Urbano,5.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0

In [3]:
import os 
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed/")
df = pd.read_parquet("comunidades_elca_longitudinal.parquet")
df.head(50)

,consecutivo_c,ola,zona,zona_2016,region,n_lideres,sexo_lider1,cargo_lider1,anos_vive_lider1,sexo_lider2,...,sequias,sequia_veces,ano_sequia,seq_acued,seq_alcan,seq_alumb,seq_vias,seq_insted,seq_psalud,seq_insdep
0,11001,1.0,Urbano,None,Bogot�,NaN,None,None,NaN,None,...,None,NaN,NaN,None,None,None,None,None,None,None
1,11002,1.0,Urbano,None,Bogot�,2.0,Hombre,Comunal,30.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
2,11003,1.0,Urbano,None,Bogot�,3.0,Hombre,Religioso,27.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
3,11004,1.0,Urbano,None,Bogot�,3.0,Hombre,Comunal,23.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
4,11005,1.0,Urbano,None,Bogot�,2.0,Mujer,Comunal,27.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
5,11006,1.0,Urbano,None,Bogot�,3.0,Mujer,Comunal,18.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
6,11007,1.0,Urbano,None,Bogot�,3.0,None,None,NaN,None,...,None,NaN,NaN,None,None,None,None,None,None,None
7,11008,1.0,Urbano,None,Bogot�,3.0,None,None,NaN,None,...,None,NaN,NaN,None,None,None,None,None,None,None
8,11009,1.0,Urbano,None,Bogot�,3.0,None,None,NaN,None,...,None,NaN,NaN,None,None,None,None,None,None,None
9,11011,1.0,Urbano,None,Bogot�,2.0,None,None,NaN,None,...,None,NaN,NaN,None,None,None,None,None,None,None
10,11101,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,20.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
11,11102,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,16.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
12,11103,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,45.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
13,11105,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,57.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
14,11106,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,30.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
15,11107,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,20.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
16,11108,1.0,Urbano,None,Atl�ntica,3.0,Mujer,Religioso,17.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
17,11109,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,14.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
18,11110,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Pol�tico,1.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
19,11111,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,25.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
20,11201,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,24.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
21,11202,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,14.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
22,11203,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,16.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
23,11204,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Otro,42.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
24,11205,1.0,Urbano,None,Atl�ntica,3.0,Hombre,Pol�tico,16.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
25,11206,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,8.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
26,11207,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,6.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
27,11208,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,20.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
28,11209,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,15.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
29,11301,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,46.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
30,11302,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Otro,20.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
31,11303,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,32.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
32,11304,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,35.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
33,11305,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,71.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
34,11306,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Otro,10.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
35,11307,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,10.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
36,11401,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,15.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
37,11402,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,3.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
38,11403,1.0,Urbano,None,Atl�ntica,3.0,Hombre,Comunal,35.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
39,11404,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,5.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
40,11405,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,7.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
41,11406,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,15.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
42,11407,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Otro,38.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
43,11408,1.0,Urbano,None,Atl�ntica,3.0,Mujer,Otro,4.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
44,11409,1.0,Urbano,None,Atl�ntica,3.0,Hombre,Comunal,5.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
45,11501,1.0,Urbano,None,Atl�ntica,2.0,Hombre,Comunal,14.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
46,11502,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Otro,36.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
47,11503,1.0,Urbano,None,Atl�ntica,3.0,Hombre,Comunal,26.0,Hombre,...,None,NaN,NaN,None,None,None,None,None,None,None
48,11504,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Religioso,33.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None
49,11505,1.0,Urbano,None,Atl�ntica,2.0,Mujer,Comunal,30.0,Mujer,...,None,NaN,NaN,None,None,None,None,None,None,None

In [4]:
import os 
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed/")
df = pd.read_parquet("hogar_elca_longitudinal_clean.parquet")
df.head(50)

,llave_n16,llave,consecutivo,consecutivo_c,hogar_n16,hogar,ola,zona,zona_2010,zona_2016,...,fechai_ano_12,vr_inicial_12,cuota_12,period_cuota_12,pacto_meses_12,cred_anombre_12,cred_aldia_12,resultado_UPA,sector_rur,envio_alim_cual
0,NaN,NaN,111001,11001,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
1,NaN,NaN,111002,11001,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
2,NaN,NaN,111003,11001,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
3,NaN,NaN,111004,11002,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
4,NaN,NaN,111006,11002,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
5,NaN,NaN,111007,11002,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
6,NaN,NaN,111008,11004,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
7,NaN,NaN,111009,11004,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
8,NaN,NaN,111010,11003,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
9,NaN,NaN,111011,11003,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
10,NaN,NaN,111012,11003,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
11,NaN,NaN,111013,11005,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
12,NaN,NaN,111014,11002,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
13,NaN,NaN,111015,11006,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
14,NaN,NaN,111016,11007,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
15,NaN,NaN,111017,11007,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
16,NaN,NaN,111018,11007,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
17,NaN,NaN,111019,11007,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
18,NaN,NaN,111020,11009,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
19,NaN,NaN,111021,11006,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
20,NaN,NaN,111022,11011,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
21,NaN,NaN,111100,11101,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
22,NaN,NaN,111101,11101,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
23,NaN,NaN,111102,11102,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
24,NaN,NaN,111103,11102,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
25,NaN,NaN,111104,11103,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
26,NaN,NaN,111105,11105,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
27,NaN,NaN,111106,11103,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
28,NaN,NaN,111107,11105,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
29,NaN,NaN,111108,11106,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
30,NaN,NaN,111109,11106,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
31,NaN,NaN,111110,11107,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
32,NaN,NaN,111111,11107,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
33,NaN,NaN,111112,11108,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
34,NaN,NaN,111113,11108,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
35,NaN,NaN,111114,11108,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
36,NaN,NaN,111115,11109,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
37,NaN,NaN,111116,11109,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
38,NaN,NaN,111117,11109,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
39,NaN,NaN,111118,11108,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
40,NaN,NaN,111120,11110,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
41,NaN,NaN,111121,11111,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
42,NaN,NaN,111122,11111,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
43,NaN,NaN,111123,11111,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
44,NaN,NaN,111124,11110,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
45,NaN,NaN,111200,11201,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
46,NaN,NaN,111201,11201,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
47,NaN,NaN,111202,11201,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
48,NaN,NaN,111203,11203,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None
49,NaN,NaN,111204,11203,NaN,NaN,1,Urbano,None,None,...,NaN,NaN,NaN,None,None,NaN,None,None,None,None

In [5]:
import os 
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed/")
df = pd.read_parquet("ninos_elca_longitudinal.parquet")
df.head(50)

,zona,ola,llaveper_n16,llaveper,llave_ID_lb,consecutivo,hogar,hogar_n16,orden,llave,...,emocional,probl_companeros,conducta,prosocial,tot_dificultades,fnac_dia,fnac_mes,fnac_ano,labusca36_48,t041_s
0,Urbano,1,NaN,NaN,11100103.0,111001,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Urbano,1,NaN,NaN,11100305.0,111003,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Urbano,1,NaN,NaN,11100404.0,111004,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Urbano,1,NaN,NaN,11100602.0,111006,NaN,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,Urbano,1,NaN,NaN,11100603.0,111006,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,Urbano,1,NaN,NaN,11100803.0,111008,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,Urbano,1,NaN,NaN,11100903.0,111009,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,Urbano,1,NaN,NaN,11101503.0,111015,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Urbano,1,NaN,NaN,11101605.0,111016,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,Urbano,1,NaN,NaN,11101606.0,111016,NaN,NaN,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,Urbano,1,NaN,NaN,11101608.0,111016,NaN,NaN,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Urbano,1,NaN,NaN,11101611.0,111016,NaN,NaN,11,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,Urbano,1,NaN,NaN,11101702.0,111017,NaN,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,Urbano,1,NaN,NaN,11101803.0,111018,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,Urbano,1,NaN,NaN,11101807.0,111018,NaN,NaN,7,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,Urbano,1,NaN,NaN,11101904.0,111019,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,Urbano,1,NaN,NaN,11102004.0,111020,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,Urbano,1,NaN,NaN,11110203.0,111102,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,Urbano,1,NaN,NaN,11110303.0,111103,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Urbano,1,NaN,NaN,11110406.0,111104,NaN,NaN,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,Urbano,1,NaN,NaN,11110604.0,111106,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,Urbano,1,NaN,NaN,11110605.0,111106,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,Urbano,1,NaN,NaN,11110704.0,111107,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,Urbano,1,NaN,NaN,11110806.0,111108,NaN,NaN,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,Urbano,1,NaN,NaN,11110904.0,111109,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,Urbano,1,NaN,NaN,11111002.0,111110,NaN,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,Urbano,1,NaN,NaN,11111205.0,111112,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Urbano,1,NaN,NaN,11111306.0,111113,NaN,NaN,6,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Urbano,1,NaN,NaN,11111708.0,111117,NaN,NaN,8,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,Urbano,1,NaN,NaN,11111709.0,111117,NaN,NaN,9,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
30,Urbano,1,NaN,NaN,11111804.0,111118,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,Urbano,1,NaN,NaN,11111805.0,111118,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
32,Urbano,1,NaN,NaN,11112003.0,111120,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
33,Urbano,1,NaN,NaN,11112103.0,111121,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
34,Urbano,1,NaN,NaN,11112104.0,111121,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,Urbano,1,NaN,NaN,11112202.0,111122,NaN,NaN,2,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,Urbano,1,NaN,NaN,11112203.0,111122,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,Urbano,1,NaN,NaN,11112303.0,111123,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
38,Urbano,1,NaN,NaN,11112405.0,111124,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
39,Urbano,1,NaN,NaN,11120003.0,111200,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,Urbano,1,NaN,NaN,11120004.0,111200,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
41,Urbano,1,NaN,NaN,11120103.0,111201,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
42,Urbano,1,NaN,NaN,11120303.0,111203,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
43,Urbano,1,NaN,NaN,11120304.0,111203,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
44,Urbano,1,NaN,NaN,11120403.0,111204,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
45,Urbano,1,NaN,NaN,11120404.0,111204,NaN,NaN,4,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46,Urbano,1,NaN,NaN,11120405.0,111204,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
47,Urbano,1,NaN,NaN,11120705.0,111207,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,Urbano,1,NaN,NaN,11121005.0,111210,NaN,NaN,5,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,Urbano,1,NaN,NaN,11121203.0,111212,NaN,NaN,3,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [1]:
import os 
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/interim/raw/elca_2010")
df = pd.read_csv("RHogar-csv.tab", sep="\t")
df.head(50)

/var/folders/mm/d4r754yx0m14_ncz8nxsvpfm0000gn/T/ipykernel_2354/2228302945.py:4: DtypeWarning: Columns (0: valor_arriendo_pagado, 1: anos_tiene_hogar, 2: ano_creo_hogar, 3: veces_cambio_vivienda, 4: vr_motocicletas, 5: vr_automoviles, 6: vr_casas, 7: ayu_fc_vr, 8: ayu_fe_vr, 9: ayu_ali_per, 10: ayu_oi_per, 11: ayu_ong_per, 12: ayu_rel_per, 13: uay_otros_cual, 14: eay_fc_vr, 15: eay_fe_per, 16: eay_alim_per, 17: eay_alim_vr, 18: eay_otras_per, 19: ing_t_actagr, 20: gto_t_actagr, 21: gan_actagr, 22: ing_t_actnag, 23: gto_t_actnag, 24: gan_actnag, 25: ing_t_vtaanimales, 26: gto_t_vtaanimales, 27: gan_vtaanimales, 28: act_vtaotros_cual, 29: act_otrosing_vr, 30: act_otrosing_cual, 31: ing_trabajo, 32: ing_arriendos, 33: meses_plazo_1, 34: conquien_cual_2, 35: destino2_2, 36: destino3_2, 37: conquien_cual_3, 38: destino2_3, 39: cuota_3, 40: vr_saldo_3, 41: conquien_cual_4, 42: destino2_4, 43: cuota_4, 44: vr_saldo_4, 45: tasa_interes_5, 46: con_quien_6, 47: destino1_6, 48: destino2_6, 49: tasa_interes_6, 50: tasa_period_6, 51: period_cuota_6, 52: tipo_deuda_7, 53: aquien_deben_7, 54: aquien_cual_7, 55: con_quien_7, 56: destino1_7, 57: tasa_period_7, 58: period_cuota_7, 59: tipo_deuda_8, 60: aquien_deben_8, 61: aquien_cual_8, 62: con_quien_8, 63: destino1_8, 64: tasa_period_8, 65: period_cuota_8, 66: act_fondos_vr, 67: act_cesantias_vr, 68: act_dineroprestado_vr, 69: act_segvida_vr, 70: act_segcosechas_vr, 71: act_segveh_vr, 72: act_segotros_vr, 73: hizo2c_1, 74: hizo3c_2, 75: hizo2c_3, 76: hizo2c_4, 77: hizo3c_4, 78: choquec_5, 79: hizo1c_5, 80: hizo2c_5, 81: hizo3c_5, 82: afectaron_hogarc_5) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("RHogar-csv.tab", sep="\t")

,ola,zona,region,id_dpto,id_mpio,id_mpioU,consecutivo_c,consecutivo,t_hogar,t_personas,...,hizo1c_5,hizo2c_5,hizo3c_5,afectaron_hogarc_5,vr_gtos_mensuales,vr_gtos_mens_alim,fhog,fexhog,riqueza_pca,tercil2010
0,1,Rural,Eje Cafetero,7,81,7081,12108,121116,1,4,...,NaN,NaN,NaN,NaN,400000,300000,3.530488,0.425435,-1.487188,2
1,1,Rural,Eje Cafetero,7,81,7081,12108,121117,1,3,...,NaN,NaN,NaN,NaN,200000,100000,3.530488,0.425435,-0.235474,3
2,1,Rural,Eje Cafetero,7,81,7081,12108,121118,1,6,...,NaN,NaN,NaN,NaN,700000,400000,3.530488,0.425435,14.124527,3
3,1,Rural,Eje Cafetero,7,81,7081,12108,121119,1,4,...,NaN,NaN,NaN,NaN,400000,300000,3.530488,0.425435,-0.451107,2
4,1,Rural,Eje Cafetero,7,81,7081,12108,121120,1,4,...,NaN,NaN,NaN,NaN,500000,320000,3.530488,0.425435,14.403579,3
5,1,Rural,Eje Cafetero,7,81,7081,12108,121121,2,5,...,NaN,NaN,NaN,NaN,500000,400000,3.530488,0.425435,15.004833,3
6,1,Rural,Eje Cafetero,7,81,7081,12109,121122,1,6,...,NaN,NaN,NaN,NaN,400000,20000,3.530488,0.425435,-0.730899,2
7,1,Rural,Eje Cafetero,7,81,7081,12109,121123,1,3,...,NaN,NaN,NaN,NaN,400000,315000,3.530488,0.425435,14.553353,3
8,1,Rural,Eje Cafetero,7,81,7081,12109,121124,1,3,...,NaN,NaN,NaN,NaN,300000,160000,3.530488,0.425435,-2.108871,1
9,1,Rural,Eje Cafetero,7,81,7081,12109,121125,1,2,...,NaN,NaN,NaN,NaN,400000,300000,3.530488,0.425435,2.477128,3
10,1,Rural,Eje Cafetero,7,81,7081,12111,121127,1,3,...,NaN,NaN,NaN,NaN,400000,200000,7.237500,0.872142,-0.099229,3
11,1,Rural,Eje Cafetero,7,81,7081,12111,121128,4,3,...,NaN,NaN,NaN,NaN,700000,500000,7.237500,0.872142,-0.064414,3
12,1,Rural,Eje Cafetero,7,81,7081,12111,121129,1,6,...,NaN,NaN,NaN,NaN,240000,150000,7.237500,0.872142,0.056110,3
13,1,Rural,Eje Cafetero,7,81,7081,12111,121130,1,2,...,NaN,NaN,NaN,NaN,500000,350000,7.237500,0.872142,-1.422965,2
14,1,Rural,Eje Cafetero,7,81,7081,12111,121131,1,3,...,NaN,NaN,NaN,NaN,300000,240000,7.237500,0.872142,13.503695,3
15,1,Rural,Eje Cafetero,7,81,7081,12112,121132,1,7,...,NaN,NaN,NaN,NaN,700000,600000,7.237500,0.872142,-0.261956,3
16,1,Rural,Eje Cafetero,7,81,7081,12112,121133,1,7,...,NaN,NaN,NaN,NaN,500000,416000,7.237500,0.872142,-1.162300,2
17,1,Rural,Eje Cafetero,7,81,7081,12112,121134,1,3,...,NaN,NaN,NaN,NaN,320000,210000,7.237500,0.872142,-1.113285,2
18,1,Rural,Eje Cafetero,7,81,7081,12112,121135,1,5,...,NaN,NaN,NaN,NaN,400000,250000,7.237500,0.872142,-1.093510,2
19,1,Rural,Eje Cafetero,7,81,7081,12112,121136,1,4,...,NaN,NaN,NaN,NaN,400000,250000,7.237500,0.872142,0.109180,3
20,1,Rural,Eje Cafetero,7,81,7081,12113,121137,1,2,...,NaN,NaN,NaN,NaN,400000,250000,7.237500,0.872142,1.795838,3
21,1,Rural,Eje Cafetero,7,81,7081,12113,121138,1,6,...,NaN,NaN,NaN,NaN,800000,600000,7.237500,0.872142,-0.565117,2
22,1,Rural,Eje Cafetero,7,81,7081,12113,121139,1,2,...,NaN,NaN,NaN,NaN,100000,70000,7.237500,0.872142,14.312628,3
23,1,Rural,Eje Cafetero,7,81,7081,12113,121141,1,3,...,NaN,NaN,NaN,NaN,400000,320000,7.237500,0.872142,-1.854765,1
24,1,Rural,Eje Cafetero,7,82,7082,12201,121201,1,5,...,NaN,NaN,NaN,NaN,450000,300000,2.881250,0.347200,14.404446,3
25,1,Rural,Eje Cafetero,7,82,7082,12201,121203,1,6,...,NaN,NaN,NaN,NaN,360000,243000,2.881250,0.347200,-1.206795,2
26,1,Rural,Eje Cafetero,7,82,7082,12201,121204,1,2,...,NaN,NaN,NaN,NaN,400000,300000,2.881250,0.347200,-0.292804,3
27,1,Rural,Eje Cafetero,7,82,7082,12201,121205,1,3,...,NaN,NaN,NaN,NaN,700000,400000,2.881250,0.347200,-0.874379,2
28,1,Rural,Eje Cafetero,7,82,7082,12201,121206,1,4,...,NaN,NaN,NaN,NaN,380000,180000,2.881250,0.347200,-0.608332,2
29,1,Rural,Eje Cafetero,7,82,7082,12201,121207,1,3,...,NaN,NaN,NaN,NaN,380000,280000,2.881250,0.347200,0.478317,3
30,1,Rural,Eje Cafetero,7,82,7082,12201,121208,1,5,...,NaN,NaN,NaN,NaN,600000,520000,2.881250,0.347200,3.557838,3
31,1,Rural,Eje Cafetero,7,82,7082,12201,121209,2,2,...,NaN,NaN,NaN,NaN,400000,290000,2.881250,0.347200,-1.120586,2
32,1,Rural,Eje Cafetero,7,82,7082,12202,121210,1,2,...,NaN,NaN,NaN,NaN,700000,500000,5.762500,0.694400,0.110890,3
33,1,Rural,Eje Cafetero,7,82,7082,12202,121211,1,8,...,NaN,NaN,NaN,NaN,640000,400000,5.762500,0.694400,-1.077264,2
34,1,Rural,Eje Cafetero,7,82,7082,12202,121212,1,4,...,NaN,NaN,NaN,NaN,900000,600000,5.762500,0.694400,1.280708,3
35,1,Rural,Eje Cafetero,7,82,7082,12202,121213,1,3,...,NaN,NaN,NaN,NaN,300000,200000,5.762500,0.694400,0.901656,3
36,1,Rural,Eje Cafetero,7,82,7082,12202,121214,1,3,...,NaN,NaN,NaN,NaN,370000,200000,5.762500,0.694400,0.593081,3
37,1,Rural,Eje Cafetero,7,82,7082,12203,121215,1,2,...,NaN,NaN,NaN,NaN,520000,320000,5.762500,0.694400,2.641650,3
38,1,Rural,Eje Cafetero,7,82,7082,12203,121216,2,2,...,NaN,NaN,NaN,NaN,420000,360000,5.762500,0.694400,1.455023,3
39,1,Rural,Eje Cafetero,7,82,7082,12203,121217,1,5,...,NaN,NaN,NaN,NaN,1000000,880000,5.762500,0.694400,-0.303472,3
40,1,Rural,Eje Cafetero,7,82,7082,12203,121218,1,5,...,NaN,NaN,NaN,NaN,750000,520000,5.762500,0.694400,2.803679,3
41,1,Rural,Eje Cafetero,7,82,7082,12203,121219,1,2,...,NaN,NaN,NaN,NaN,2000000,400000,5.762500,0.694400,3.928778,3
42,1,Rural,Eje Cafetero,7,82,7082,12204,121220,1,3,...,NaN,NaN,NaN,NaN,600000,400000,5.762500,0.694400,0.299395,3
43,1,Rural,Eje Cafetero,7,82,7082,12204,121221,1,2,...,NaN,NaN,NaN,NaN,300000,200000,5.762500,0.694400,-0.132089,3
44,1,Rural,Eje Cafetero,7,82,7082,12204,121222,1,4,...,NaN,NaN,NaN,NaN,450000,320000,5.762500,0.694400,-0.881996,2
45,1,Rural,Eje Cafetero,7,82,7082,12204,121223,1,3,...,NaN,NaN,NaN,NaN,350000,200000,5.762500,0.694400,-0.898083,2
46,1,Rural,Eje Cafetero,7,82,7082,12204,121224,1,4,...,NaN,NaN,NaN,NaN,550000,350000,5.762500,0.694400,-0.884962,2
47,1,Rural,Eje Cafetero,7,82,7082,12205,121225,1,4,...,NaN,NaN,NaN,NaN,300000,250000,2.881250,0.347200,-0.851186,2
48,1,Rural,Eje Cafetero,7,82,7082,12205,121226,1,4,...,NaN,NaN,NaN,NaN,360000,280000,2.881250,0.347200,1.067454,3
49,1,Rural,Eje Cafetero,7,82,7082,12205,121227,1,3,...,NaN,NaN,NaN,NaN,550000,400000,2.881250,0.347200,1.082982,3