In [ ]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed")
choques_elca_longitudinal = pd.read_parquet(
    "choques_elca_longitudinal.parquet",
    engine="pyarrow"
)
choques_elca_longitudinal

,llave_n16,llave,consecutivo,hogar_n16,hogar,ola,zona,total_choques,choque_abandono_del_hogar_por_parte_de_un_menor_de_18_anos,choque_abandono_del_que_era_jefe_del_hogar_o_del_conyuge,...,resp_se_cambiaron_a_una_vivienda_mas_economica,resp_se_endeudaron_con_familiares_o_amigos,resp_se_endeudaron_con_un_banco_o_entidad_financiera,resp_se_reubicaron,resp_tomaron_un_seguro,resp_tuvieron_que_cambiar_de_municipio_o_departamento,resp_uno_o_mas_miembros_del_hogar_cambiaron_de_residencia,resp_uno_o_mas_miembros_del_hogar_salieron_del_pais,resp_usaron_algun_seguro,resp_vendieron_bienes_o_activos
0,NaN,NaN,111003,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
1,NaN,NaN,111006,NaN,NaN,1,Urbano,3.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
2,NaN,NaN,111007,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
3,NaN,NaN,111011,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
4,NaN,NaN,111012,NaN,NaN,1,Urbano,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16396,2.262870e+09,22628701.0,226287,1.0,NaN,3,Rural,2.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16397,2.262870e+09,22628701.0,226287,2.0,NaN,3,Rural,3.0,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
16398,2.262880e+09,22628801.0,226288,1.0,NaN,3,Rural,1.0,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
16399,2.262890e+09,22628901.0,226289,1.0,NaN,3,Rural,3.0,NaN,NaN,...,NaN,0.0,2.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0
16400,2.266210e+09,22662101.0,226621,1.0,NaN,3,Rural,6.0,NaN,NaN,...,NaN,0.0,0.0,NaN,NaN,0.0,NaN,NaN,0.0,0.0

In [3]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed")
gastos_elca_longitudinal = pd.read_parquet(
    "gastos_elca_longitudinal.parquet",
    engine="pyarrow"
)
gastos_elca_longitudinal

,llave_n16,llave,consecutivo,hogar_n16,hogar,ola,zona,total_items_comprados,total_gasto,total_gasto_obt,...,regalo_ropa_para_hombre_mujer_nino_y_nina,regalo_salchichas_jamon_mortadela_salchichon_y_otras_carnes_frias_preparadas,regalo_salud_de_todos_los_miembros_del_hogar_incluya_medicina_prepagada,regalo_salud_medicamentos_examenes_consultas_etc,regalo_salud_terapias_hospitalizaciones_etc_diferentes_a_las_reportadas_en_403_l,regalo_seguro_contra_incendios_o_contra_robo_de_la_vivienda_o_vehiculos_de_uso_del_hogar,regalo_servicio_domestico_por_dias,regalo_servicios_publicos_acueducto_alcantarillado_y_aseo_energia_electrica_telefono_fijo_gas_etc,regalo_tela_para_vestuario_u_otros_usos,regalo_vehiculo_moto_para_uso_del_hogar
0,NaN,NaN,111001,NaN,NaN,1,Urbano,11.0,495500.0,0.0,...,0,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,0
1,NaN,NaN,111002,NaN,NaN,1,Urbano,13.0,527200.0,0.0,...,0,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,0
2,NaN,NaN,111003,NaN,NaN,1,Urbano,17.0,3832500.0,0.0,...,0,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,0
3,NaN,NaN,111004,NaN,NaN,1,Urbano,17.0,1873000.0,0.0,...,0,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,0
4,NaN,NaN,111006,NaN,NaN,1,Urbano,10.0,241500.0,0.0,...,0,NaN,0.0,NaN,NaN,NaN,NaN,0,NaN,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27927,2.262870e+09,22628701.0,226287,1.0,NaN,3,Rural,30.0,1643700.0,4000.0,...,0,0.0,NaN,0.0,0.0,0.0,0.0,0,0.0,0
27928,2.262870e+09,22628701.0,226287,2.0,NaN,3,Rural,19.0,626700.0,20000.0,...,0,0.0,NaN,0.0,0.0,0.0,0.0,0,0.0,0
27929,2.262880e+09,22628801.0,226288,1.0,NaN,3,Rural,27.0,865400.0,39000.0,...,0,0.0,NaN,0.0,0.0,0.0,0.0,0,0.0,0
27930,2.262890e+09,22628901.0,226289,1.0,NaN,3,Rural,31.0,1337550.0,103000.0,...,0,0.0,NaN,0.0,0.0,0.0,0.0,0,0.0,0
27931,2.266210e+09,22662101.0,226621,1.0,NaN,3,Rural,36.0,1884100.0,0.0,...,0,0.0,NaN,0.0,0.0,0.0,0.0,0,0.0,0

In [4]:
import os
import pandas as pd
os.chdir("/Users/macbook/Documents/Documentos/tesis_vulnerabilidad/data/processed")
RActivos_hogar_unido = pd.read_parquet(
    "RActivos_hogar_unido.parquet",
    engine="pyarrow"
)
RActivos_hogar_unido

,ola,consecutivo,tiro_animal,n_tiro_animal,vr_alquiler_tiro_animal,tractor,n_tractor,vr_alquiler_tractor,otros_tractor,n_otros_tractor,...,n_estanque,picapasto,n_picapasto,colmenas,n_colmenas,n_otros_anim,n_otro_cual,hogar_n16,llave_n16,n_invernadro
0,1,121116,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,NaN
1,1,121117,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,NaN
2,1,121118,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,NaN
3,1,121119,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,NaN
4,1,121120,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,None,NaN,None,NaN,NaN,None,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12805,3,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.262870e+09,NaN
12806,3,226287,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,2.0,2.262870e+09,NaN
12807,3,226288,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.262880e+09,NaN
12808,3,226289,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,Si,3.0,No,NaN,NaN,,1.0,2.262890e+09,NaN
12809,3,226621,No,NaN,NaN,No,NaN,NaN,No,NaN,...,NaN,No,NaN,No,NaN,NaN,,1.0,2.266210e+09,1.0